opt_in_rules:
  - all

disabled_rules:
  - closure_body_length
  - explicit_acl
  - explicit_top_level_acl
  - explicit_type_interface
  - no_grouping_extension
  - no_magic_numbers
  - required_deinit
  - strict_fileprivate
  - switch_case_on_newline

identifier_name:
  excluded:
    - id
    - to
